language: rust
cache:
  - cargo

install:
  - rustup component add rustfmt
script:
  - cargo test
  - cargo fmt -- --check
  - docker build -t discord-mods-bot .

# Publish the Docker image to the infra AWS registry
before_deploy:
  - pip install --user awscli
deploy:
  provider: script
  script: sh ci/publish-docker.sh
  on:
    branch: master
